### ISSUE TITLE
There is already a Construct with name 'Network' in GitlabRunnerStack

### ISSUE THREAD

**Issue by jonnedeprez** [pepperize/cdk-autoscaling-gitlab-runner#374]
Deploying two `GitlabRunnerAutoscaling` constructs in the same CDK project (for example one with runners for light workloads and one for heavy workloads) is currently not possible. Every `GitlabRunnerAutoscaling` instantiates a new `Network` construct called "Network", a new `SecurityGroup` called "ManagerSecurityGroup", ... and those names will clash.
Can this Network not be shared between two `GitlabRunnerAutoscaling` constructs, just like for the cache bucket?

**Comment by pflorek** [comment]
Hey @jonnedeprez 

sure, it can be refactored to use the construct's singleton pattern.

Which CFN resources have conflicting names? Let's CFN manage the name or suffix them with the node's id.

If you only need two different gitlab job runner configs, a single manager should be sufficient.

**Comment by jonnedeprez** [comment]
Hi @pflorek , thank you for your fast reaction! I had a look at it, but my problem is actually slightly different. On https://github.com/pepperize/cdk-autoscaling-gitlab-runner/blob/9b1139a289f6e54189210b089c51a18c247bcc67/src/runner/runner.ts#L136 a Network construct is instantiated with a CDK id "Network". If I wanted to create two `GitlabRunnerAutoscaling' constructs in one stack, those two names would clash (CDK error). The same counts for line 141, 145 and 159. Wouldn't it be better to apply the pattern for the bucket (line 131) also to these constructs. If that were the case, I could deploy a stack with two autoscaling groups in the same network, managed by the same manager instance, and sharing a cache bucket. It would be the cheapest way to use two different runner configurations in my project. 

In any case, we're already using your project and it works great. Many thanks!

**Comment by pflorek** [comment]
Hey @jonnedeprez ,

yes, if you just want two runners the cheapest way, then follow this https://github.com/pepperize/cdk-autoscaling-gitlab-runner#multiple-runners-configuration _The AutoScalingGroup is for the manager/coordinator which spins up the job runner instances on demand or by the amazonec2 driver autoscaling configuration._

If you want two manager/coordinator instances then add two `GitlabRunnerAutoscaling` to the stack. The construct tree should be fixed by https://github.com/pepperize/cdk-autoscaling-gitlab-runner/pull/376 If you use this option, you may pass the Vpc and Bucket to the construct https://github.com/pepperize/cdk-autoscaling-gitlab-runner/blob/main/test/runner/runner.test.ts#L288-L329

**Comment by jonnedeprez** [comment]
Ok thanks!
